---
- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# Iptables v1.8.0-1.8.4 have a specific bug with K3s. https://github.com/k3s-io/k3s/issues/3117
- name: If iptables v1.8.0-1.8.4, warn user  # noqa ignore-errors
  when:
    - ansible_facts.packages['iptables'] is defined
    - ansible_facts.packages['iptables'][0]['version'] is version('1.8.5', '<')
    - ansible_facts.packages['iptables'][0]['version'] is version('1.7.9', '>')
  ansible.builtin.fail:
    msg:
      - "Warning: Iptables {{ ansible_facts.packages['iptables'][0]['version'] }} found."
      - "Add '--prefer-bundled-bin' to extra_server_args variable to use the bundled iptables binary."
  ignore_errors: true

- name: Enable cgroup via boot commandline if not already enabled
  # when: lookup('fileglob', '/boot/firmware/cmdline.txt', errors='warn') | length == 0
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  notify: Reboot Pi

- name: Install Ubuntu Raspi Extra Packages
  ansible.builtin.apt:
    # Fixes issues in newer Ubuntu where VXLan isn't setup right.
    # See: https://github.com/k3s-io/k3s/issues/4234
    name: linux-modules-extra-raspi
    update_cache: true
    state: present
  when: "ansible_distribution_version is version('20.10', '>=')"