---
- name: Configure Server Environments
  hosts: homelab
  gather_facts: true
  become: true
  roles:
    - linux_node
  tags:
    - linuxEnv

# - name: Setup Tailscale Connection
#   hosts: skybreaker
#   gather_facts: true
#   become: true
#   roles:
#     - tailscale

- name: Setup SMB Share
  hosts: bondsmith
  gather_facts: true
  become: true
  roles:
    - nas
  vars:
    nas_user: k3s-nas-user
  tags: 
    - smb

- name: Confiure the K3S Nodes
  hosts: master_nodes
  gather_facts: true
  become: true
  roles:
    - k3s_prereq
  tags: 
    - k3s

# - name: Setup K3S Server
#   hosts: master_nodes
#   gather_facts: true
#   become: true
#   roles:
#     - k3s_server
