---
# Guide: https://www.raspberrypi.com/tutorials/nas-box-raspberry-pi-tutorial/
- name: Configure Samba
  hosts: bondsmith
  vars:
    nas_user: k3s-nas-user
  tasks:
    - name: Installing Samba
      ansible.builtin.apt:
        pkg:
          - samba
          - samba-common-bin
    - name: Creating /nas/ dir for share
      file:
        path: "/nas"
        state: directory
    - name: Creating Samba config file
      copy:
        dest: "/etc/samba/smb.conf"
        content: |
          [nas]
          path=/nas
          writeable=Yes
          create mask=0777
          directory mask=0777
          public=no
      become: yes
    - name: Restart smb service
      ansible.builtin.systemd_service:
        name: smbd
        state: restarted
        daemon_reload: true
      become: yes
    - name: Add a {{ nas_user }}
      become: yes
      ansible.builtin.user:
        name: "{{ nas_user }}"
        password: $y$j9T$c2LILE8lQM8Sh.RwCeshK0$a3GNvRDCYgH1p3UDO7YnORdXR3gGdbJTGKdfvX9B/hA
    - name: Add {{ nas_user }} to smbpasswd
      become: yes
      shell: "(echo {{ nas_user }}; echo {{ nas_user }}) | smbpasswd -s -a {{ nas_user }}"
